### ISSUE TITLE
⚙️ 와인 vivino 평점 가져오기

### ISSUE THREAD

**Issue by jeongyun1206** [Drink-Easy/backend#93]
## 설명
와인에 대한 vivino 평점 조회가 필요.

## 체크리스트
- [x] vivino 사이트에서 평점 가져오기

## 기한
2024.12.31

## 참고자료
vivino 평점 보기 : https://www.vivino.com/explore?e=eJwrL4mOtTVUKwdRRgAgBwRK

**Comment by jeongyeon0208** [comment]
vivino 연동 조회 API 생성은 현재 수준에서 어려워, vivino에서 평점 추출 진행중
